type PharmacyCashier = {
  cashierId: number;
  phoneNumber: string;
  gender: 'Male' | 'Female';
  branchName: string;
  activeStatus: boolean;
  monthlySalaryPaid: boolean;
  monthlyPaymentAmount: number;
};

const PharmacyCashiers: PharmacyCashier[] = [
  {
    cashierId: 1,
    phoneNumber: '1234567890',
    gender: 'Male',
    branchName: 'Branch A',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3000,
  },
  {
    cashierId: 2,
    phoneNumber: '9876543210',
    gender: 'Female',
    branchName: 'Branch B',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3200,
  },
  {
    cashierId: 3,
    phoneNumber: '5554443333',
    gender: 'Male',
    branchName: 'Branch C',
    activeStatus: false,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 4,
    phoneNumber: '9998887777',
    gender: 'Female',
    branchName: 'Branch D',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 2800,
  },
  {
    cashierId: 5,
    phoneNumber: '3332221111',
    gender: 'Male',
    branchName: 'Branch E',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3100,
  },
  {
    cashierId: 6,
    phoneNumber: '7776665555',
    gender: 'Female',
    branchName: 'Branch F',
    activeStatus: false,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 7,
    phoneNumber: '4445556666',
    gender: 'Male',
    branchName: 'Branch G',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 2900,
  },
  {
    cashierId: 8,
    phoneNumber: '8889990000',
    gender: 'Female',
    branchName: 'Branch H',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3300,
  },
  {
    cashierId: 9,
    phoneNumber: '1234432156',
    gender: 'Male',
    branchName: 'Branch I',
    activeStatus: true,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 10,
    phoneNumber: '5566778899',
    gender: 'Female',
    branchName: 'Branch J',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 2950,
  },
  {
    cashierId: 11,
    phoneNumber: '1112223333',
    gender: 'Male',
    branchName: 'Branch K',
    activeStatus: false,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 12,
    phoneNumber: '9876543210',
    gender: 'Female',
    branchName: 'Branch L',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3050,
  },
  {
    cashierId: 13,
    phoneNumber: '4443332222',
    gender: 'Male',
    branchName: 'Branch M',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3200,
  },
  {
    cashierId: 14,
    phoneNumber: '8887776666',
    gender: 'Female',
    branchName: 'Branch N',
    activeStatus: false,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 15,
    phoneNumber: '5554443333',
    gender: 'Male',
    branchName: 'Branch O',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3100,
  },
  {
    cashierId: 16,
    phoneNumber: '2223334444',
    gender: 'Female',
    branchName: 'Branch P',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3400,
  },
  {
    cashierId: 17,
    phoneNumber: '6667778888',
    gender: 'Male',
    branchName: 'Branch Q',
    activeStatus: true,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 18,
    phoneNumber: '9998887777',
    gender: 'Female',
    branchName: 'Branch R',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 2900,
  },
  {
    cashierId: 19,
    phoneNumber: '3332221111',
    gender: 'Male',
    branchName: 'Branch S',
    activeStatus: false,
    monthlySalaryPaid: false,
    monthlyPaymentAmount: 0,
  },
  {
    cashierId: 20,
    phoneNumber: '7776665555',
    gender: 'Female',
    branchName: 'Branch T',
    activeStatus: true,
    monthlySalaryPaid: true,
    monthlyPaymentAmount: 3150,
  },
];

export default PharmacyCashiers;
